easy_admin:
    site_name: 'Kazou RMT'
    formats:
        datetime: 'd/m/Y H:i:s'
    design:
        brand_color: '#6db649'
        assets:
            favicon: 'favicon.ico'
            css: ['css/easyAdmin.css']
        menu:
            - { label: 'Website' }
            - { entity: 'Link', icon: 'link'}
            - { label: 'Algemeen' }
            - { entity: 'User', icon: 'user'}
    list:
        max_results: 50
    entities:
        User:
            class: AppBundle\Entity\User
            label: 'Gebruikers'
            list:
                title: '%%entity_label%%'
        Link:
            class: AppBundle\Entity\Link
            label: 'Knoppen hoofdpagina'
            list:
                title: '%%entity_label%%'
                fields:
                    - { property: 'name', label: 'admin.name' }
                    - { property: 'enabled', label: 'admin.enabled' }
                    - { property: 'createdBy' }
                    - { property: 'updatedBy' }
                    - { property: 'updatedAt' }
                    - { property: 'updatedAt' }
            new:
                title: '%%entity_label%%'
                fields:
                    - { property: 'name', label: 'admin.name' }
                    - { property: 'link', label: 'admin.link' }
                    - { property: 'order', label: 'admin.order' }
                    - { property: 'enabled', label: 'admin.enabled' }
            edit:
                title: '%%entity_label%%'
                fields:
                    - { property: 'name', label: 'admin.name' }
                    - { property: 'link', label: 'admin.link' }
                    - { property: 'enabled', label: 'admin.enabled' }
