imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

easy_admin:
    site_name: 'Kazou RMT'
    formats:
        datetime: 'd/m/Y H:i:s'
    design:
        brand_color: '#6db649'
        assets:
            favicon: 'favicon.ico'
            css: ['css/easyAdmin.css']
        menu:
            - { label: 'Algemeen' }
            - { entity: 'User', icon: 'user'}
            - { entity: 'Vacancy', icon: 'question'}
            - { label: 'Onkosten' }
            - { entity: 'Trip', icon: 'car'}
            - { entity: 'TripGroup', icon: 'filter'}
            - { entity: 'TripActivity', icon: 'list'}
            - { label: 'Onkosten verwerken', icon: 'paper-plane', children: [ { entity: 'TripValidate', icon: 'check' }, { entity: 'TripExport', icon: 'download'}] }
            - { entity: 'TripManual', icon: 'book' }
            - { label: 'Overigen' }
            - { entity: 'Region', icon: 'map-marker'}
    list:
        max_results: 50
    entities:
        Trip:
            class: AppBundle\Entity\Trip
            label: 'Ritten'
            disabled_actions: ['new']
            list:
                title: '%%entity_label%%'
                fields: ['user', 'activity', 'from', 'to', 'date']
                sort: 'createdAt'
                actions:
#                    - { name: 'search', icon: 'search', label: '' }
                    - { name: 'edit', icon: 'pencil', label: '' }
                    - { name: 'show', icon: 'eye', label: '' }
                    - { name: '-delete' }
            edit:
                fields:
                    - { property: 'user'}
                    - { property: 'group'}
                    - { property: 'activity'}
                    - { property: 'from', type: 'text'}
                    - { property: 'to', type: 'text'}
                    - { property: 'date'}
                    - { property: 'transportType', type: 'text'}
                    - { property: 'company', type: 'text'}
                    - { property: 'comment', type: 'textarea'}
                    - { property: 'price'}
                    - { property: 'status', type: 'choice', type_options: { choices: '%trip_status%' }, help: 'Weet waar je mee bezig bent als je de status hier weizigd. De status zou automatisch aangepast moeten worden door onkosten te verwerken of te exporteren.</br> Deze waarde manueel aanpassen kan tot gevolg hebben dat onkosten niet bij de boekhouding geraken.'}
            show:
                fields:
                    - user
                    - group
                    - activity
                    - from
                    - to
                    - date
                    - transportType
                    - company
                    - { property: 'tickets', template: 'easyAdmin/typeTemplates/imageArray.html.twig' }
                    - comment
                    - price
                    - status
        TripGroup:
            class: AppBundle\Entity\TripGroup
            label: 'Groepen'
            list:
                title: '%%entity_label%%'
                sort: ['order', 'ASC']
                fields:
                    - { property: 'order' }
                    - { property: 'code' }
                    - { property: 'nameHierarchy', label: 'Naam', template: 'easyAdmin/typeTemplates/hierarchyType.html.twig' }
                    - { property: 'startDate' }
                    - { property: 'endDate' }
                    - { property: 'location' }
            new:
                title: '%%entity_label%%'
                fields:
                    - { type: 'section', label: 'admin.general' }
                    - { property: 'code', label: 'admin.code' }
                    - { property: 'name', label: 'admin.name' }
                    - { property: 'parent', label: 'admin.parent' }
                    - { property: 'tripActivity', label: 'admin.tripActivity' }
                    - { type: 'section', label: 'admin.forHolidays' }
                    - { property: 'startDate', label: 'admin.startDate' }
                    - { property: 'endDate', label: 'admin.endDate' }
                    - { property: 'location', label: 'admin.location' }
            edit:
                title: '%%entity_label%%'
                fields:
                    - { type: 'section', label: 'admin.general' }
                    - { property: 'code', label: 'admin.code' }
                    - { property: 'name', label: 'admin.name' }
                    - { property: 'parent', label: 'admin.parent' }
                    - { property: 'tripActivity', label: 'admin.tripActivity' }
                    - { type: 'section', label: 'admin.forHolidays' }
                    - { property: 'startDate', label: 'admin.startDate' }
                    - { property: 'endDate', label: 'admin.endDate' }
                    - { property: 'location', label: 'admin.location' }
        TripActivity:
            class: AppBundle\Entity\TripActivity
            label: 'Activiteiten'
            list:
                title: '%%entity_label%%'
            new:
                title: '%%entity_label%%'
                fields:
                    - { property: 'code', label: 'admin.code' }
                    - { property: 'name', label: 'admin.name' }
        TripValidate:
            class: AppBundle\Entity\Trip
            label: 'Onkosten valideren'
            list:
                title: '%%entity_label%%'
            templates:
                list: 'easyAdmin/TripValidate/list.html.twig'
        TripExport:
            class: AppBundle\Entity\Trip
            label: 'Onkosten exporteren'
            list:
                title: '%%entity_label%%'
            templates:
                list: 'easyAdmin/TripExport/list.html.twig'
        TripManual:
            class: AppBundle\Entity\Trip
            label: 'Handleiding'
            list:
                title: '%%entity_label%%'
            templates:
                list: 'easyAdmin/TripManual/list.html.twig'
        User:
            class: AppBundle\Entity\User
            label: 'Gebruikers'
            list:
                title: '%%entity_label%%'
        Vacancy:
            class: AppBundle\Entity\Vacancy
            label: 'Vacatures'
            list:
                title: '%%entity_label%%'
        Region:
            class: AppBundle\Entity\Region
            label: 'Verbonden'
            list:
                title: '%%entity_label%%'
