easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
#    resource: "@AppBundle/Controller/EasyAdmin/AdminController.php"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

