# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     app.form.registration:
            class: AppBundle\Form\RegistrationFormType
            tags:
                - { name: form.type }

     app.redirect_after_registration_subscriber:
            class: AppBundle\EventListener\RedirectAfterRegistrationSubscriber
            autowire: true
            tags:
                - { name: kernel.event_subscriber }

     app.fos_user.oauth_provider:
         # Change the class according to the location of the FOSUBUserProvider class
         class: AppBundle\Service\FOSUBUserProvider
         arguments: ['@fos_user.user_manager',{facebook: facebook_id}]
