# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
            class: AppBundle\Form\RegistrationFormType
            tags:
                - { name: form.type }

    app.service.facebook_user_provider:
            class: AppBundle\Service\FacebookUserProvider
            arguments:
                - '@Doctrine\ORM\EntityManagerInterface'
                - '@session'
                - '@Symfony\Component\Routing\RouterInterface'
                - '%facebook_oauth_redirect%'
                - '%facebook_app_id%'
                - '%facebook_app_secret%'
                - '%upload_directory%'
            autowire: true

    app.security.login_form_authenticator:
            class: AppBundle\Security\LoginFormAuthenticator
            autowire: true

    app.security.facebook_form_authenticator:
            class: AppBundle\Security\FacebookFormAuthenticator
            autowire: true

    app.doctrine.hash_password_listener:
            class: AppBundle\Doctrine\HashPasswordListener
            autowire: true
            tags:
                - { name: doctrine.event_listener, event: prePersist }
                - { name: doctrine.event_listener, event: preUpdate }
